spring:
  datasource:
    url: jdbc:mysql://yingdiandian.mysql.rds.aliyuncs.com:3306/eye_cloud?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
    username: yingdd
    password: Yingdd2015

  redis:
    host: 127.0.0.1
    password:
    timeout: 6000
    port: 6379

  jpa:
    show-sql: true

push:
  member:
    appKey: f074801c6b577599220cd9aa
    masterSecret: 05c0f6b00719edd5b5aca9f3
    isProduction: false
  agent:
    appKey: d113221d3f5a8e02a65291b1
    masterSecret: aed6cf700fa4e73edc2ef38d
    isProduction: false
  admin:
    appKey: a7912caeccc91efcb62e2ce9
    masterSecret: 943d0149c356433026579af8
    isProduction: false